version: '3'
services:
  db1:
    image: mysql
    volumes:
      - ./src/main/resources/db1/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 13306:3306
  db2:
    image: postgres
    volumes:
      - ./src/main/resources/db2/initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 15432:5432
