spring:
  datasources:
    one:
      jdbc-url: jdbc:mysql://127.0.0.1:13306/db1
      username: root
      pool-name: DataSource-1 
    two:
      jdbc-url: jdbc:postgresql://127.0.0.1:15432/db2
      username: postgres
      pool-name: DataSource-2
